[project]
name = "fastkit-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Codevelo", email = "info@codevelo.io" }
]
[tool.uv]
package = "fastkit_auth"
src-dir = "src"
requires-python = ">=3.12"
dependencies = [
    "fastapi-users>=15.0.3",
    "fastkit-core>=0.3.4",
]


[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "alembic",
]
