[project]
name = "fastkit-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Codevelo", email = "info@codevelo.io" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
fastkit-auth = "fastkit_auth:main"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
