[project]
name = "fastkit-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Codevelo", email = "info@codevelo.io" }
]

requires-python = ">=3.12"
dependencies = [
    "fastkit-core>=0.3.5",
    "mailbridge>=2.0.0",
    "passlib>=1.7.4",
    "pydantic[email]>=2.12.5",
    "pyjwt>=2.11.0",
]


[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "alembic",
    "asyncpg>=0.31.0",
    "psycopg2-binary>=2.9.11",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
